### ISSUE TITLE
[yeha] 1장을 읽고 프로젝트에 반영해보고 싶은/반영한 내용이 있나요? 

### ISSUE THREAD

**Issue by hayeonhee** [de-vook/The-Essence-of-Object-Orientation#1]

**Comment by hayeonhee** [comment]
저는 쥬스메이커 프로젝트를 진행하며 반영했던 경험이 있습니다. 
1장에 나오는 주문 -> 커피 제조하는 예시를 보며 제가 작성한 코드가 하나의 기능을 수행하고 있지 못하다는 것을 깨달았습니다. 
그래서 쥬스를 만드는 메서드가 1) 재고 확인 2) 쥬스 제조(재고 차감) 의 두 개의 기능을 수행하고 있다는 것을 자각하고, 각각 메서드로 분리했습니다. 
하지만 메서드끼리 메세지를 주고 받도록 (언제든 교체되기 쉽도록) 만들지는 못했습니다. 
현재 진행하는 계산기 프로젝트에서 메서드끼리 필요한 것을 파라미터와 리턴으로 주고 받도록 설계해보려고 합니다.

**Comment by yanghojoon** [comment]
예하가 책을 보시고 메서드의 기능을 분리하셨다는 것을 듣고 궁금해서 질문했던 부분입니다. 

책 p/28에 보면 `한 사람이 동시에 여러 역할을 수행할 수 있다.` 라고 나와 있는데 이 부분은 SOLID 원칙 같은 것을 위배하는 것 아닌가 궁금했습니다. 

하지만 고사리께서 이 부분은 코드의 재사용성을 의미하는 것으로 이해했다고 말씀해주셨습니다. 

또한 예하도 역할 안에서 해야하는 일이 책임이라고 이해하셨다고 말씀해주셨습니다. 
즉, 하나의 메서드가 하나의 기능을 하는 것은 책임의 영역이라고 이해했습니다.
