### ISSUE TITLE
[호댕 & 고사리] 먼저 객체의 행동을 결정하고 그 후에 행동에 적절한 상태를 선택하라는 것의 의미가 무엇일까요??

### ISSUE THREAD

**Issue by yanghojoon** [de-vook/The-Essence-of-Object-Orientation#18]
P/65에 보면 먼저 객체의 행동을 결정하고 그 후에 행동에 적절한 상태를 선택하게 된다고 해서, `TDD를 할 때처럼 없는 프로퍼티를 상상해서 먼저 함수를 만드는 것이 좋은 것일까?` 라고 처음엔 생각했습니다. 

그런데 고사리와 이야기를 나누며 프로퍼티를 먼저 만들지 않고 함수를 만든다기 보단 행동 명세를 작성해보고 프로퍼티를 만드는 것으로 이해를 했습니다!
혹시 저희가 이해한 것이 맞을까요?

**Comment by jsim27** [comment]
저도 비슷하게 이해했습니다.
이 객체가 해야 할 행동을 함수로 정의해나가는 과정에서, 행동의 전제조건이 될 상태 프로퍼티가 필요하겠다고 판단되면 그 시점에 프로퍼티를 만드는 것으로 이해했습니다.

**Comment by Ldoy** [comment]
전체맥락을 파악하지 않고 쓰는 글이라 주제에 벗어날 수 있지만 남겨주신 코멘트들을 읽다가 이런 흐름이 아닐까 싶어 공유해 봅니다. 

프로젝트 명세서 : 주스가게 사장님은 썩지 않은 사과를 이용해 주스를 만들어야한다. 
1. `좋은 사과` 와 `썩은 사과`를 구분할 수 있는 인스턴스가 필요하다. 
2. 사과를 구분하는 `행동(메서드)`을 정의한다. 
3. 사과를 구분하려면 `눈`이 필요하다는 것을 깨닫는다. -> `눈` 속성을 정의한다. 

```swift
//1.
struct Owner {
    //3.
   var eyes = Eyes()

    //2.
    func decideGoodApple() {
       // eyes 속성을 이용하여 좋은 사과를 판단
    }
}
```

**Comment by hayeonhee** [comment]
나무와 타코캣의 의견과 같습니다! 
`행동 명세를 먼저 작성하고, 그 행동을 하기 위해 필요한 (데이터를 저장하는) 상태를 가지는` 순서여야 한다 고 이해했습니다

**Comment by yeahg-dev** [comment]
저도 나무, 타코캣의 의견에 동의합니다~
협력하기 위해 필요한 행동을 먼저 결정하고, 행동에 필요한 상태를 파악하고, 상태를 정의하는 것이라고 이해했습니다.
